all:
	$(MAKE) -C tensor

run-simx:
	$(MAKE) -C tensor run-simx

run-rtlsim:
	$(MAKE) -C tensor run-rtlsim

run-opae:
	$(MAKE) -C tensor run-opae

clean:
	$(MAKE) -C tensor clean

clean-all:
	$(MAKE) -C tensor clean-all
